// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BoardColum: typeof import('./src/components/BoardColum.vue')['default']
    BoardColumn: typeof import('./src/components/BoardColumn.vue')['default']
    BoardCreateColumn: typeof import('./src/components/BoardCreateColumn.vue')['default']
    BoardCreateForm: typeof import('./src/components/BoardCreateForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
